[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_claimer = "DfmArRxQL4usBuAv4QFA7PVhXf3c1KLremcoDDww9DG4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "./keypairs/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migrations/initialize.ts"
expand_bitmap = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migrations/expand_bitmap.ts"
spl_create_fund_mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migrations/spl_create_fund_mint.ts"
spl_approve = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migrations/spl_approve.ts"
print_public_keys = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 migrations/print_public_keys.ts"
