[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_claimer = "DfmArRxQL4usBuAv4QFA7PVhXf3c1KLremcoDDww9DG4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
# cluster = "localnet"
wallet = "./keypairs/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
